name: Label Sync

on:
  label:
    types: [created, edited, deleted]
  push:
    branches:
      - master

jobs:
  label-sync:
    name: Label Sync
    runs-on: ubuntu-latest
    env:
      GITHUB_API_TOKEN: ${{ secrets.GITHUB_API_TOKEN }}
      LABEL_REPO_SOURCE: hyphacoop/demo-repo
      LABEL_REPO_TARGETS: patcon/label-sync-demo patcon/archive-demo
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: '7.3'
      - run: |
          composer require vanilla/github-sync
          for target in $LABEL_REPO_TARGETS; do
            ./vendor/bin/github-sync labels --from $LABEL_REPO_SOURCE --to $target --delete prune
          done
